<template>
  <article class="thermal" :aria-label="`Receipt ${receipt.receipt_number}`">
    <header class="t-head">
      <img v-if="issuer?.logo_url && !logoFailed" class="t-logo" :src="issuer.logo_url" alt="" @load="$emit('ready')" @error="onLogoError">
      <div v-else class="t-monogram" aria-hidden="true">{{ initials }}</div>
      <strong class="t-centre">{{ issuer?.name || 'Blood centre' }}</strong>
      <span v-if="issuer?.address" class="t-small">{{ issuer.address }}</span>
      <span v-if="issuer?.phone" class="t-small">{{ issuer.phone }}</span>
    </header>

    <div class="t-rule" />

    <p class="t-title">PAYMENT ACKNOWLEDGEMENT RECEIPT</p>
    <p v-if="receipt.voided" class="t-void">VOID — {{ receipt.void_reason }}</p>

    <dl class="t-kv">
      <div><dt>Receipt No.</dt><dd>{{ receipt.receipt_number }}</dd></div>
      <div><dt>Date</dt><dd>{{ when(receipt.payment?.paid_at || receipt.issued_at) }}</dd></div>
      <div v-if="receipt.request?.reference_number"><dt>Request</dt><dd>{{ receipt.request.reference_number }}</dd></div>
      <div v-if="receipt.statement"><dt>Statement</dt><dd>{{ receipt.statement.document_number }}</dd></div>
      <div v-if="receipt.payer_name"><dt>Received from</dt><dd>{{ receipt.payer_name }}</dd></div>
      <div v-if="receipt.request?.patient_name"><dt>Patient</dt><dd>{{ receipt.request.patient_name }}</dd></div>
    </dl>

    <template v-if="receipt.lines?.length">
      <div class="t-rule t-rule--dashed" />
      <table class="t-lines">
        <tbody>
          <tr v-for="(line, i) in receipt.lines" :key="i">
            <td>
              {{ line.component_name }}
              <span class="t-small">{{ line.quantity }} × {{ pesos(line.unit_price) }}</span>
            </td>
            <td class="t-num">{{ pesos(line.line_total) }}</td>
          </tr>
        </tbody>
      </table>
    </template>

    <div class="t-rule t-rule--dashed" />

    <dl class="t-kv t-totals">
      <div v-if="receipt.statement"><dt>Bill total</dt><dd>{{ pesos(receipt.statement.total_amount) }}</dd></div>
      <div><dt>Balance before</dt><dd>{{ pesos(receipt.balance_before) }}</dd></div>
      <div class="t-big"><dt>AMOUNT RECEIVED</dt><dd>{{ pesos(receipt.amount_paid) }}</dd></div>
      <div><dt>Method</dt><dd>{{ receipt.payment?.method_label || receipt.payment_method_label || '—' }}</dd></div>
      <template v-if="receipt.payment?.amount_tendered">
        <div><dt>Cash tendered</dt><dd>{{ pesos(receipt.payment.amount_tendered) }}</dd></div>
        <div><dt>Change</dt><dd>{{ pesos(receipt.payment.change_given) }}</dd></div>
      </template>
      <div class="t-strong"><dt>Balance after</dt><dd>{{ pesos(Math.max(Number(receipt.balance_after ?? 0), 0)) }}</dd></div>
    </dl>

    <p class="t-note">
      {{ receipt.is_partial ? 'Part payment. The balance above is still due before blood is released.' : 'The bill is settled by this payment.' }}
    </p>

    <div class="t-rule" />

    <dl class="t-kv">
      <div><dt>Cashier</dt><dd>{{ receipt.received_by || 'Payment provider' }}</dd></div>
      <div v-if="receipt.payment?.cash_session_number"><dt>Shift</dt><dd>{{ receipt.payment.cash_session_number }}</dd></div>
      <div v-if="receipt.replaces_receipt_number"><dt>Replaces</dt><dd>{{ receipt.replaces_receipt_number }}</dd></div>
    </dl>

    <p class="t-foot">
      This acknowledges payment received. It is not a BIR official receipt.<br>
      Generated by RedAgos
    </p>
  </article>
</template>

<script setup lang="ts">
/*
 * A Payment Acknowledgement Receipt laid out for an 80mm thermal printer.
 *
 * Read from the receipt's frozen snapshot, as the A4 PDF is, so the two say
 * the same thing. Headed by the issuing centre's own logo — the one the
 * receipt was issued with — or its initials when it has none. Black on white
 * only: a thermal printer has no colour.
 *
 * Emits `ready` once the logo has loaded (or there is none), so a print page
 * does not print before the logo is on it.
 */
import type { PaymentReceiptSummary } from '~/types/bloodRequest'
import { facilityInitials, pesos } from '~/utils/billing'

const props = defineProps<{ receipt: PaymentReceiptSummary }>()
const emit = defineEmits<{ ready: [] }>()

const issuer = computed(() => props.receipt.issuing_facility ?? null)
const initials = computed(() => facilityInitials(issuer.value?.name))
const logoFailed = ref(false)

function onLogoError() {
  logoFailed.value = true
  emit('ready')
}

function when(iso: string | null | undefined): string {
  return iso ? new Date(iso).toLocaleString('en-PH', { dateStyle: 'medium', timeStyle: 'short' }) : '—'
}

onMounted(() => {
  if (!issuer.value?.logo_url) emit('ready')
})
</script>

<style scoped>
/* Black on white, sized for 80mm paper (about 72mm printable). */
.thermal {
  width: 72mm; margin: 0 auto; padding: 3mm 0; color: #000; background: #fff;
  font-family: ui-monospace, 'DejaVu Sans Mono', Menlo, Consolas, monospace; font-size: 11px; line-height: 1.35;
}
.t-head { display: flex; flex-direction: column; align-items: center; text-align: center; gap: 2px; }
.t-logo { max-width: 40mm; max-height: 18mm; object-fit: contain; margin-bottom: 2px; filter: grayscale(1); }
.t-monogram { width: 12mm; height: 12mm; border: 1.5px solid #000; border-radius: 3mm; display: grid; place-items: center; font-weight: 800; font-size: 15px; margin-bottom: 2px; }
.t-centre { font-size: 13px; }
.t-small { display: block; font-size: 10px; }
.t-rule { border-top: 1px solid #000; margin: 6px 0; }
.t-rule--dashed { border-top-style: dashed; }
.t-title { text-align: center; font-weight: 800; margin: 0 0 4px; font-size: 11.5px; }
.t-void { text-align: center; font-weight: 800; border: 1.5px solid #000; padding: 2px; margin: 0 0 4px; }
.t-kv { margin: 0; }
.t-kv > div { display: flex; justify-content: space-between; gap: 6px; }
.t-kv dt { margin: 0; }
.t-kv dd { margin: 0; text-align: right; font-weight: 600; overflow-wrap: anywhere; }
.t-lines { width: 100%; border-collapse: collapse; }
.t-lines td { padding: 1px 0; vertical-align: top; }
.t-num { text-align: right; white-space: nowrap; }
.t-totals .t-big { font-size: 13px; font-weight: 800; border-top: 1px solid #000; border-bottom: 1px solid #000; padding: 2px 0; margin: 2px 0; }
.t-totals .t-big dd { font-weight: 800; }
.t-strong { font-weight: 800; }
.t-note { margin: 6px 0 0; font-size: 10px; text-align: center; }
.t-foot { margin: 8px 0 0; font-size: 9.5px; text-align: center; }
</style>
